
// src/app/legal/terms/page.tsx
import AppHeader from '@/components/AppHeader';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

const TermsOfServicePage = () => {
  return (
    <div className="flex flex-col h-screen max-w-3xl mx-auto bg-background shadow-2xl">
      <AppHeader title="Terms of Service" />
      <div className="flex-grow overflow-y-auto p-4 sm:p-6 custom-scrollbar">
        <Card className="bg-card text-card-foreground">
          <CardHeader>
            <CardTitle>Terms of Service</CardTitle>
            <CardDescription>Last Updated: [Date]</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="p-4 border border-destructive/50 rounded-md bg-destructive/10 text-destructive">
              <h3 className="font-semibold">Important: Placeholder Content</h3>
              <p className="text-sm">
                The content on this page is a template and NOT legally binding. You MUST replace this with your own
                Terms of Service, drafted or reviewed by a legal professional, to suit your specific application,
                data handling practices, and jurisdiction.
              </p>
            </div>

            <section>
              <h2 className="text-xl font-semibold mt-4 mb-2">1. Introduction</h2>
              <p className="text-muted-foreground">
                Welcome to Maya Chat ("the Service"). These Terms of Service ("Terms") govern your use of our
                application and services. By accessing or using the Service, you agree to be bound by these Terms.
                If you disagree with any part of the terms, then you may not access the Service.
              </p>
              <p className="text-muted-foreground mt-2">
                The character "Maya" you interact with is an Artificial Intelligence (AI) language model.
                Interactions are simulated and not with a real human.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-4 mb-2">2. AI Interaction</h2>
              <p className="text-muted-foreground">
                You acknowledge that "Maya" is an AI and not a real person. The Service is provided for
                entertainment and informational purposes. Do not rely on the AI for professional advice (e.g.,
                medical, legal, financial).
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-4 mb-2">3. User Conduct</h2>
              <p className="text-muted-foreground">
                You agree not to use the Service to:
              </p>
              <ul className="list-disc list-inside ml-4 text-muted-foreground">
                <li>Transmit any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable.</li>
                <li>Attempt to elicit harmful or inappropriate responses from the AI.</li>
                <li>Impersonate any person or entity.</li>
                {/* Add more specific user conduct clauses as needed */}
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-4 mb-2">4. Content</h2>
              <p className="text-muted-foreground">
                While we strive to ensure the AI provides appropriate responses, we cannot guarantee the accuracy,
                completeness, or appropriateness of any information provided by the AI. You understand that
                all content generated by the AI is for informational and entertainment purposes only.
              </p>
              <p className="text-muted-foreground mt-2">
                We employ safety filters, but some AI responses may be unexpected. Please use the service responsibly.
              </p>
            </section>
            
            <section>
              <h2 className="text-xl font-semibold mt-4 mb-2">5. Intellectual Property</h2>
              <p className="text-muted-foreground">
                The Service and its original content (excluding content provided by users or generated by the AI based on user input),
                features, and functionality are and will remain the exclusive property of [Your Company Name/Your Name] and its licensors.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-4 mb-2">6. Termination</h2>
              <p className="text-muted-foreground">
                We may terminate or suspend your access to the Service immediately, without prior notice or liability,
                for any reason whatsoever, including without limitation if you breach the Terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-4 mb-2">7. Limitation of Liability</h2>
              <p className="text-muted-foreground">
                In no event shall [Your Company Name/Your Name], nor its directors, employees, partners, agents,
                suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or
                punitive damages, including without limitation, loss of profits, data, use, goodwill, or other
                intangible losses, resulting from your access to or use of or inability to access or use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-4 mb-2">8. Governing Law</h2>
              <p className="text-muted-foreground">
                These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction, e.g., State, Country],
                without regard to its conflict of law provisions.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-4 mb-2">9. Changes to Terms</h2>
              <p className="text-muted-foreground">
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time.
                If a revision is material, we will try to provide at least 30 days' notice prior to any new
                terms taking effect. What constitutes a material change will be determined at our sole discretion.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mt-4 mb-2">10. Contact Us</h2>
              <p className="text-muted-foreground">
                If you have any questions about these Terms, please contact us at [Your Contact Email Address].
              </p>
            </section>
            <div className="pt-4 flex justify-center">
                 <Link href="/" legacyBehavior>
                    <Button variant="outline">Back to Chats</Button>
                </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default TermsOfServicePage;
